trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: backendServiceArm
    value: 'Azure-Terraform-Connection'
  - name: backendAzureRmResourceGroupName
    value: 'terraform-state-rg'
  - name: backendAzureRmStorageAccountName
    value: 'tfstate767361244'
  - name: backendAzureRmContainerName
    value: 'tfstate'
  - name: backendAzureRmKey
    value: 'terraform.tfstate'
  - name: TF_VERSION
    value: '1.6.6'

stages:
  - stage: Destroy
    displayName: 'Destroy Infrastructure'
    jobs:
      - deployment: DestroyInfrastructure
        displayName: 'Destroy All Resources'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: 'Terraform Destroy'
                  inputs:
                    azureSubscription: $(backendServiceArm)
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Install Terraform
                      wget -q https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
                      unzip -q terraform_$(TF_VERSION)_linux_amd64.zip
                      sudo mv terraform /usr/local/bin/
                      
                      # Get storage account key
                      export ARM_ACCESS_KEY=$(az storage account keys list \
                        --resource-group $(backendAzureRmResourceGroupName) \
                        --account-name $(backendAzureRmStorageAccountName) \
                        --query '[0].value' -o tsv)
                      
                      # Initialize
                      terraform init \
                        -backend-config="resource_group_name=$(backendAzureRmResourceGroupName)" \
                        -backend-config="storage_account_name=$(backendAzureRmStorageAccountName)" \
                        -backend-config="container_name=$(backendAzureRmContainerName)" \
                        -backend-config="key=$(backendAzureRmKey)"
                      
                      # Destroy
                      terraform destroy -auto-approve
                      
                      echo "✅ Infrastructure destroyed successfully!"
